// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9lGybBcaLxz5HOdiZOlxtYpp8Rpp-Dw',
    appId: '1:650693791997:web:d7a2045830a5dc1a71ee94',
    messagingSenderId: '650693791997',
    projectId: 'allergy-detect-9d658',
    authDomain: 'allergy-detect-9d658.firebaseapp.com',
    storageBucket: 'allergy-detect-9d658.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ2pAgwWJvnQGBrHP65gHRaxqWu3czzxU',
    appId: '1:650693791997:android:00a028e80ed9038271ee94',
    messagingSenderId: '650693791997',
    projectId: 'allergy-detect-9d658',
    storageBucket: 'allergy-detect-9d658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVsrA2TQd9Y6fWCRjlKQKCZzAlnu8Ps4',
    appId: '1:650693791997:ios:9f69c7bc6bcee85b71ee94',
    messagingSenderId: '650693791997',
    projectId: 'allergy-detect-9d658',
    storageBucket: 'allergy-detect-9d658.firebasestorage.app',
    androidClientId: '650693791997-l5cvtagrc1scjrlmg82hl895gr3i0i65.apps.googleusercontent.com',
    iosClientId: '650693791997-843pfdu0m38rdrd76c3kku9la5r6q45a.apps.googleusercontent.com',
    iosBundleId: 'com.example.allergyDetectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVsrA2TQd9Y6fWCRjlKQKCZzAlnu8Ps4',
    appId: '1:650693791997:ios:9f69c7bc6bcee85b71ee94',
    messagingSenderId: '650693791997',
    projectId: 'allergy-detect-9d658',
    storageBucket: 'allergy-detect-9d658.firebasestorage.app',
    androidClientId: '650693791997-l5cvtagrc1scjrlmg82hl895gr3i0i65.apps.googleusercontent.com',
    iosClientId: '650693791997-843pfdu0m38rdrd76c3kku9la5r6q45a.apps.googleusercontent.com',
    iosBundleId: 'com.example.allergyDetectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR9lGybBcaLxz5HOdiZOlxtYpp8Rpp-Dw',
    appId: '1:650693791997:web:2b309ac828229dee71ee94',
    messagingSenderId: '650693791997',
    projectId: 'allergy-detect-9d658',
    authDomain: 'allergy-detect-9d658.firebaseapp.com',
    storageBucket: 'allergy-detect-9d658.firebasestorage.app',
  );
}
